<!-- Use this variable to set the maintained by e-mail address -->
        <?php $maintainedby = "scott@pdx.edu"; ?>

<table border="0" cellpadding="0" cellspacing="0">
<tr>

<td valign="top">

	<table border="0" cellpadding="10" cellspacing="0"><tr><td nowrap>

<P><a href="whois.php">About Us</a>
<P><a href="services.php">Services</a>
<P><a href="help.php">Help!</a>
<P><a href="news.php">News</a>
<P><a href="policies.php">Policies</a>
<P><a href="software.php">Software</a>
<P><a href="forms.php">Forms</a>

<!--
<P><a href="https://banweb.pdx.edu/oprd/owa/hwgkwbis.P_WWWLogin">Student Records</a>

<P><FORM name="QuickIndex">
      <SELECT name="URL"
      onChange="if(options[selectedIndex].value)

      window.location.href=

      (options[selectedIndex].value)"
      size="1">
      <OPTION selected>Go to site:</OPTION>
      <OPTION>---CNS LINKS---</OPTION>
      <OPTION value="policies.php">policies page</OPTION>
      <OPTION value="software.php">software page</OPTION>
      <OPTION value="forms.php">forms page</OPTION>
      <OPTION value="http://www.cns.pdx.edu/action/">- action form</OPTION>
      <OPTION value="http://www.rams.pdx.edu/irnsoftware/current/softwarerequest/softreqcurrent.cfm">- software request</OPTION>
      <OPTION value="http://www.account.pdx.edu/">- account form</OPTION>
      <OPTION value="http://www.lists.pdx.edu">- email lists</OPTION>
      <OPTION>---EMAIL---</OPTION>
      <OPTION value="http://gwweb.pdx.edu/cgi-bin/GW5/GWWEB.EXE?GET-CONTEXT&HTMLVER=HTML3">student groupwise</OPTION>
      <OPTION value="https://webmail.pdx.edu/">webmail</OPTION>
      <OPTION value="http://mail.pdx.edu/cgi-bin/GW5/GWWEB.EXE?GET-CONTEXT&HTMLVER=HTML3">faculty groupwise</OPTION>
      <OPTION>---PSU LINKS---</OPTION>
      <OPTION value="http://www.pdx.edu/">psu</OPTION>
      <OPTION value="http://www.oit.pdx.edu/">oit</OPTION>
      <OPTION value="http://www.irsmain.pdx.edu/">irs-main</OPTION>
      <OPTION value="http://www.lib.pdx.edu/">psu library</OPTION>
      <OPTION value="https://banweb.pdx.edu/oprd/owa/hwgkwbis.P_WWWLogin">student records</OPTION>
      </SELECT>
</FORM>
-->

	</td></tr></table>


</td>

<td bgcolor="336633" height="100%"" valign="top">
<img src="/common-files/blank.gif" width="1"></td>

<td valign="top">
	<table border="0" cellpadding="10" cellspacing="0"><tr><td>